# Generated by Django 5.2.14 on 2026-05-10 21:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Events_even_search__eb153a_gin'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE "Events_event"
                SET search_vector =
                        to_tsvector(
                                'simple',
                                coalesce(title, '') || ' ' ||
                                coalesce(description, '')
                        );
                """,
            reverse_sql="""
                UPDATE "Events_event"
                SET search_vector = NULL;
                """
        ),

        migrations.RunSQL(
            sql="""
                CREATE FUNCTION event_search_vector_update()
                    RETURNS trigger AS $$
                BEGIN
                            NEW.search_vector
                :=
                                to_tsvector(
                                    'simple',
                                    coalesce(NEW.title, '') || ' ' ||
                                    coalesce(NEW.description, '')
                                );

                RETURN NEW;
                END
                        $$
                LANGUAGE plpgsql;
                """,
            reverse_sql="""
                        DROP FUNCTION IF EXISTS event_search_vector_update CASCADE;
                    """
        ),

        migrations.RunSQL(
            sql="""
                CREATE TRIGGER event_search_vector_trigger
                    BEFORE INSERT OR
                UPDATE
                    ON "Events_event"
                    FOR EACH ROW
                    EXECUTE FUNCTION event_search_vector_update();
                """,
            reverse_sql="""
                        DROP TRIGGER IF EXISTS event_search_vector_trigger
                        ON "Events_event";
                    """
        ),
    ]
